### ISSUE TITLE
Add Support For All DLSS DLLs

### ISSUE THREAD

**Issue by twindragon6** [Recol/DLSS-Updater#10]
Currently only support is available for nvngx_dlss.dll DLLs.
Support for nvngx_dlssg.dll and nvngx_dlssd.dll are missing.

https://www.techpowerup.com/download/nvidia-dlss-3-frame-generation-dll/
https://www.techpowerup.com/download/nvidia-dlss-3-ray-reconstruction-dll/
https://www.techpowerup.com/download/nvidia-dlss-dll/

**Comment by Recol** [comment]
I intend to add support for these relatively soon, features that are to be released are listed [here](https://github.com/Recol/DLSS-Updater?tab=readme-ov-file#future-features).

**Comment by Recol** [comment]
Support for these is now included from 2.0.0 onwards.
