### ISSUE TITLE
Keep a log of changes

### ISSUE THREAD

**Issue by mkaatman** [Recol/DLSS-Updater#11]
Might be nice to have a text log in the directory with all the changes since the shell disappears upon completion.

**Comment by Recol** [comment]
This shouldn't be the case, you have to press the Enter key to exit at the end.

**Comment by mkaatman** [comment]
You know it was sitting a while and I did press enter before it ended and that must have triggered it.

**Comment by Recol** [comment]
Happens :) It's a neat idea, i'll consider the possibility for the future though.

**Comment by Recol** [comment]
This is now included from version 2.1.0.
