### ISSUE TITLE
Will this trigger anti-cheat systems?

### ISSUE THREAD

**Issue by mkaatman** [Recol/DLSS-Updater#12]
I noticed a lot of multiplayer games were getting updated and I was curious if anti-cheat would get triggered?

**Comment by Recol** [comment]
Short answer no, long answer is there's no definite answer either way. Some versions of EAC will block DLSS and others won't, there's too many to provide a universal answer. Please see the EAC disclaimer [here](https://github.com/Recol/DLSS-Updater?tab=readme-ov-file#easy-anti-cheat).
