### ISSUE TITLE
Escape From Tarkov - integrity failed after updating DLSS

### ISSUE THREAD

**Issue by Jayowski** [Recol/DLSS-Updater#13]
Hey there,

As in the title - after updating the DLSS in Escape from Tarkov, the next time I opened its launcher it says my game lost integrity, effectively forcing me to re-install it (~30GB)

**Comment by Recol** [comment]
Will deploy an update to fix this, give me around 5 minutes thanks.

**Comment by Recol** [comment]
@Jayowski This should be resolved with [version 2.0.3](https://github.com/Recol/DLSS-Updater/releases/tag/V2.0.3), please report back if this is still occurring after cheers.

**Comment by killer777909** [comment]
Is it even safe for EFT? Like, they ban you if they find files from SPT client in your games directory.

**Comment by Glipts** [comment]
Are you planning to fix the updater in Tarkov?

**Comment by Recol** [comment]
@Glipts If you can paste/screenshot the terminal output this can be done.

**Comment by DraimCiDo** [comment]
[dlss_updater.log](https://github.com/user-attachments/files/16912234/dlss_updater.log)

@Recol

**Comment by Recol** [comment]
@DraimCiDo Thanks for the log, will release a patch over the weekend to resolve it.

**Comment by Recol** [comment]
@DraimCiDo Hi all and others, i've deployed a (hopeful fix) to the issue, if you could report back on this [version](https://github.com/Recol/DLSS-Updater/releases/tag/V2.1.1) it'd be appreciated thanks.

**Comment by Glipts** [comment]
@Recol I need just to start exe DLSS_Updater or I need to do something else?

**Comment by Glipts** [comment]
![image](https://github.com/user-attachments/assets/c7ee77b1-8485-4fda-a478-3689f616224f)
same error 103003

**Comment by Recol** [comment]
@Glipts Experimental fix 2, please try this updated binary: https://github.com/Recol/DLSS-Updater/releases/tag/V2.1.1 (same version), and attach the log if this still does not work.

**Comment by Glipts** [comment]
In tarkov launcher error without code 
[dlss_updater.log](https://github.com/user-attachments/files/16913922/dlss_updater.log)

**Comment by DraimCiDo** [comment]
[dlss_updater.log](https://github.com/user-attachments/files/16913933/dlss_updater.log)
According to your program logs, everything is going well.

In the launcher itself, most likely there is some kind of check for .dll files, and when replaced nvngx_dlss.dll, the game does not run (usually error 103003)

I tried to find the logs of the game, and inprinciple I found them, but it is the logs of the process of the game (logging into the game, game settings, routing and etc), but the process of checking the launcher and the overall logs of the launcher as I understand there is no.

**Comment by Recol** [comment]
Hi all, I have a few theories why this is occuring, I do not own the game so I am not able to test this fully (neither will I buy the game solely to test this), I'll dedicate some time to see if I can see the underlying issue later during the week.

**Comment by DraimCiDo** [comment]
@Recol 
I can give access to game if that helps.
We will need to contact me in Discord (I've already sent you friend invites).

**Comment by Recol** [comment]
Special thanks to @DraimCiDo, this issue is now fixed with version [2.2.0](https://github.com/Recol/DLSS-Updater/releases/tag/V2.2.0).
