### ISSUE TITLE
Changing the logic of the whitelist

### ISSUE THREAD

**Issue by LiaNdrY** [Recol/DLSS-Updater#14]
I suggest making a whitelist in a separate txt or csv file and pulling it from the repository so as not to update the application every time because of some new game added.

**Comment by BlackGrimReaper** [comment]
I suggest doing the same with the path list so that we can avoid repeating prompts for different game folders in our system. It will also help automate the process. Additionally, if we want to add any other directories, we can simply add them manually to the text file.

**Comment by Recol** [comment]
@BlackGrimReaper I will not add this functionality as it complicates things heavily without not breaking in built features the program has.

**Comment by Recol** [comment]
@LiaNdrY This has now been included, the whitelist is now contained here: https://github.com/Recol/DLSS-Updater-Whitelist/tree/main
