### ISSUE TITLE
Stuck on the 'download and install the update' screen

### ISSUE THREAD

**Issue by Graylies047** [Recol/DLSS-Updater#15]
Version v2.0.5 insists it is actually v2.0.4 and forces me to update to another v2.0.5 that still thinks it is v2.0.4
![Captura de tela 2024-09-01 193507](https://github.com/user-attachments/assets/84d2b921-ee07-4c80-ad80-a843fbc1740b)

**Comment by Recol** [comment]
Hi there, apologies, was a minor regression in the release, if you could redownload the binary this should be resolved :)
