### ISSUE TITLE
Please exclude Squad and Squad 44 (formely Post Scriptum) from updater list

### ISSUE THREAD

**Issue by mikolaj612** [Recol/DLSS-Updater#17]
Hello, both games are using EAC and if you update DLSS files manually or using your tool for example DLSS will not work again.
It's been like that since they introduced DLSS support, same goes for FSR and XeSS.

I hope that's not a problem for you :)
Anyway - great app.

Have a nice day!

PS: I almost forgot, you can also blacklist Chivalry 2 from the list - DLSS replacement is only working with MS Store version, Epic and Steam version also rely on EAC integrity checks.

**Comment by Recol** [comment]
@mikolaj612 Thanks for the report, they're now excluded with version 2.0.6: https://github.com/Recol/DLSS-Updater/releases/tag/V2.0.6
