### ISSUE TITLE
2 issues & 1 feedback

### ISSUE THREAD

**Issue by xHybred** [Recol/DLSS-Updater#2]
- On reddit you state you're going to apply a global block for EAC. Don't. EAC has an option to block DLSS dll, it's not a global block. Some EAC games will work, some won't. Some thing with ReShade which uses dll's, some EAC games block it others not. So unfortunately you will have to manually check this or rely on user reports for your blacklist.

- Battle.net verifies files everytime you open the launcher, thus instantly replaces the updated dll so you need to update the dll after the launcher has been opened unlike the Steam version of there games

- Your program is great but if you combined it with my DLSSEnhancer mod (which is a fork of another mod) with a whitelist created for compatible games it would improve image quality or performance further of DLSS. Especially if you gave players an option to preselect which preset of the enhancer they want, since theirs many. But this is just feedback/additional functionality: https://github.com/xHybred/DLSSEnhancer

Best of luck!

**Comment by Recol** [comment]
> On reddit you state you're going to apply a global block for EAC. Don't. EAC has an option to block DLSS dll, it's not a global block. Some EAC games will work, some won't. Some thing with ReShade which uses dll's, some EAC games block it others not. So unfortunately you will have to manually check this or rely on user reports for your blacklist.

Hm, okay, i had a suspicion but thanks for the confirmation with EAC. Rather painstaking but it is what it is. 

> Battle.net verifies files everytime you open the launcher, thus instantly replaces the updated dll so you need to update the dll after the launcher has been opened unlike the Steam version of there games

With Battle.net i am not liking the idea of having to check for it to be running on instantiation... difficult one to approach, i'll add a disclaimer for it that the user has have the launcher already booted, dpuble edged sword for it either way the more i think about it.

> Your program is great but if you combined it with my DLSSEnhancer mod (which is a fork of another mod) with a whitelist created for compatible games it would improve image quality or performance further of DLSS. Especially if you gave players an option to preselect which preset of the enhancer they want, since theirs many. But this is just feedback/additional functionality: https://github.com/xHybred/DLSSEnhancer

Thanks it's appreciated :), i am mindful that something like this would be very useful, i'm limited currently with Pyinstaller which is the main gripe with if (xyz thing can be compatible without totally frying the build process), will take it as a more possible longer term thing.
