### ISSUE TITLE
Starship Troopers Extermination needs whitelisting

### ISSUE THREAD

**Issue by AxelJaeger-XIII** [Recol/DLSS-Updater#24]
Hi, as titled Starship Troopers Extermination needs whitelisting because Easy Anti Cheat disables DLSS otherwise please, thank you!

**Comment by Recol** [comment]
Thanks for the report, it's been whitelisted in [version 2.0.9](https://github.com/Recol/DLSS-Updater/releases/tag/V2.0.9).

**Comment by AxelJaeger-XIII** [comment]
Hello, seems like it's still getting updated:
<img width="962" alt="Immagine 2024-09-03 194219" src="https://github.com/user-attachments/assets/4fa4d99e-7b5f-45b2-a63f-68990a76ed06">

**Comment by Recol** [comment]
@AxelJaeger-XIII Will be because it's one word, regex match issue, give me 5 minutes.

**Comment by Recol** [comment]
@AxelJaeger-XIII If you could try the [updated binary](https://github.com/Recol/DLSS-Updater/releases/tag/V2.0.9) it should be excluded now.

**Comment by AxelJaeger-XIII** [comment]
Yes, it is now correctly excluded, thank you!

**Comment by Recol** [comment]
No problem :)
