### ISSUE TITLE
better logs output

### ISSUE THREAD

**Issue by ethaniel86** [Recol/DLSS-Updater#25]
i ran this updater this is the summary

------------------------------------------
Summary:
Games updated successfully:
 - Diablo IV - Steam
 - Palworld - Steam

Successful backups:
 - Diablo IV: D:\SteamLibrary\steamapps\common\Diablo IV\nvngx_dlss.dlsss
 - Palworld: D:\SteamLibrary\steamapps\common\Palworld\Pal\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dlsss

Games skipped:
 - Diablo IV - Steam (Reason: Update failed)

Press Enter to exit...
------------------------------------------

So diablo 4 successfully updated or failed? I'm confused.

**Comment by Recol** [comment]
This is because it is including FG/RR DLL's, so technically, yes it's both, it's not built to manage the context of this yet, it will be adjusted in the future.

**Comment by ethaniel86** [comment]
btw, how do we rollback? 
Would be nice to have a gui / cmd line options to select which game(s) to perform update to latest DLSS and rollback, instead of proceed immediately for all games.

**Comment by Recol** [comment]
Due to the way the integration works i am not planning on adding manual support for updating it, this will be included however for restoring, when it's added.

**Comment by Recol** [comment]
Integrated with the latest version https://github.com/Recol/DLSS-Updater/releases/tag/V2.2.0.
