### ISSUE TITLE
Is this bannable?

### ISSUE THREAD

**Issue by Kotoezhh** [Recol/DLSS-Updater#27]
I would guess it isnt, but its better to be safe than sorry. 
Sorry for bothering and again thanks in advance <3

**Comment by Recol** [comment]
Please see this [issue](https://github.com/Recol/DLSS-Updater/issues/12).

**Comment by Kotoezhh** [comment]
> Please see this [issue](https://github.com/Recol/DLSS-Updater/issues/12).
I've read this issue, but didnt find the answer ;/
I understand it might not work, thats not the question tho
The question is not will it work or not, its more like is there any chances that i can get banned if it works in the end?
in my understanding it should either work fine, launch the game wout the dlss or wont launch at all, and thers no chance to get banned, but i just wanna be sure 
Only thing i found online is this post on other project : https://github.com/Nukem9/dlssg-to-fsr3/issues/181
But its more radical, because you literally change one thing to another, and i think its not the same as updating an existing thing
but in the end its changing the files anyway, so thats why im asking: is there any risk in your opinion?
The tool just updated a few games like Hunt and TheFinals, and i dont really care (i can revert changes), but if theres no chance to get banned i will at least test how it feels/works etc. if theres a chance ill just revert the files, thats it :p

**Comment by Recol** [comment]
@Kotoezhh As with software you run your own risk, i take no liability for if it happens, there is no such thing as a 'non risk' factor, it is the same risk level as updating it yourself. This software is just a automatic way of doing that, it's not like DLSSG-FSR. If you aren't personally comfortable doing it, then this software doesn't change that risk, if you are then there's no different risk either way.

**Comment by Kotoezhh** [comment]
Ight, so basically PROBABLY nothing will happen but that ofc is on me if it will 
I understand that you are not responsible for anything, just wanted to get your opinion on that 
Thanks for your time and your work on this project
