### ISSUE TITLE
Tomb Raider low fps

### ISSUE THREAD

**Issue by BaturaET** [Recol/DLSS-Updater#28]
In **Shadow Of The Tomb Raider** it changed from 60/70fps to 40fps in any quality preset, it changed from version _2,3,2,0_ to _3,7,20,0_.
![C__Users_breno_Downloads_DLSS Updater 2 0 6_update_DLSS_Updater exe 04_09_2024 11_53_38](https://github.com/user-attachments/assets/1ef9e7f4-9a03-45a7-a008-62cc36ec8ab4)

In **Rise Of The Tomb Raider** I believe there was an improvement in image, but without noticeable losses, that was good!
![C__Users_breno_Downloads_DLSS Updater 2 0 6_update_DLSS_Updater exe 04_09_2024 11_40_20](https://github.com/user-attachments/assets/00d8d6f0-1536-45fb-9a56-5863f00b2176)

**Comment by Recol** [comment]
Not something i will action, SOTR has too many variables, for example supporting DX11/12 to know what's going on, simply revert the old DLL file in this instance.
