### ISSUE TITLE
How to Update for the "Green" Steam Version?

### ISSUE THREAD

**Issue by Lagbag** [Recol/DLSS-Updater#29]
I want to use Dlss Updater for the "green" version of Steam. Could you provide recommendations or instructions on how to upgrade to the green version?

Thank you in advance for your help!

With best wishes,
LagBag

**Comment by Recol** [comment]
@Lagbag What exactly do you mean by Green version of Steam?

**Comment by Lagbag** [comment]
@Recol I mean torrent

**Comment by Recol** [comment]
@Lagbag Not something I can do something about, only the official client is supported, you can put the file path manually in place of one of the launchers.

**Comment by Lagbag** [comment]
@Recol Could you explain how to figure out which games can be upgraded using this tool? For example, I'm not sure if Skyrim is supported or not. Sorry for the questions, I just have trouble understanding guides in English. Could you briefly and clearly explain how to check which games are supported and how to use this tool?

**Comment by Recol** [comment]
Please read the Q&A - there is no specific game support, if a game **supports** DLSS, then it is supported unless it is on the whitelist.
