### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by Calinou** [Recol/DLSS-Updater#3]
The project's current license is [CC BY-NC-SA 4.0](https://github.com/Recol/DLSS-Updater/blob/main/LICENSE), which does not follow the [open source definition](https://opensource.org/osd) due to restrictions on commercial use. Additionally, the license is not designed for use on software (but on art or documentation instead). See [this page](https://freedomdefined.org/Licenses/NC) as for why this can be an issue.

Could you look into using a license that is friendly to open source developers such as MIT, please? See [Choose a License](https://choosealicense.com/) for more information. Thanks in advance :slightly_smiling_face:

**Comment by Recol** [comment]
The license has now been migrated to [the Apache License 2.0](https://github.com/Recol/DLSS-Updater/blob/main/LICENSE), will keep this issue open for the time being.
