### ISSUE TITLE
Planetside 2 DLSS DLL replaced on startup

### ISSUE THREAD

**Issue by m0unds** [Recol/DLSS-Updater#30]
Just a heads up - every launch of Planetside 2 replaces the updated DLSS DLL, so it should probably be whitelisted.

Here's the launcher's log entry:

`Found 1 file(s) to update.
Replacing nvngx_dlss.dll
Finished downloading 8,689,442 bytes in 0.994 seconds (8,741,893 bytes per second)`

When installed via steam, it installs to steamapps\common\planetside 2
Path for the dlss library is steamapps\common\planetside 2\nvngx_dlss.dll
ships with 2.2.18.0

I can provide other details if necessary.

Thanks for the tool, it's great.

**Comment by Recol** [comment]
@m0unds Many thanks, Planetside 2 will be whitelisted on the next release.

**Comment by Recol** [comment]
Fixed with version [2.2.0](https://github.com/Recol/DLSS-Updater/releases/tag/V2.2.0).
