### ISSUE TITLE
BlackMythWuKong DLSS Update Failed

### ISSUE THREAD

**Issue by Smile035** [Recol/DLSS-Updater#31]
BlackMythWukong - Steam (DLSS DLL) (Reason: Update failed)
BlackMythWukong - Steam (DLSS Ray Reconstruction DLL) (Reason: Update failed)
BlackMythWukong - Steam (DLSS Frame Generation DLL) (Reason: Update failed)

**Comment by DraimCiDo** [comment]
@Smile035 Show full log

**Comment by DraimCiDo** [comment]
Yes, you already have an updated DLSS in this game.

It's just that @Recol didn't add the label "Game has already been updated".
