### ISSUE TITLE
Ability to scan for non-launcher games

### ISSUE THREAD

**Issue by rayman3003** [Recol/DLSS-Updater#36]
Could u please add an option that allows DLSS-Updater to add & scan dlls of non-launcher games?

Bcuz there are so many games that didn't came from those 6 popular launchers (stores), & need to be updated too.

**Comment by Recol** [comment]
@rayman3003 This is already supported, simply put the associated path of one of the non launchers inside the launcher ones instead.

**Comment by rayman3003** [comment]
What about supporting them, by not putting them inside the launcher folder?

For example by dragging & doping the folder of the game?!!
