### ISSUE TITLE
Throne & Liberty does not like modified DLSS

### ISSUE THREAD

**Issue by ghuff07** [Recol/DLSS-Updater#38]
I would recommend adding Throne & Liberty as it does not like a modified DLSS fille (DLSS is disabled if the file is modified).

**Comment by Recol** [comment]
@ghuff07 Thanks for the report, would you mind reporting the file structure it uses (i.e. just the stored path if possible) thanks so it can be excluded.

**Comment by ghuff07** [comment]
C:\Program Files (x86)\Steam\steamapps\common\Throne and Liberty\TL\Plugins\DLSS\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll

C:\Program Files (x86)\Steam\steamapps\common\Throne and Liberty\TL\Plugins\Streamline\Binaries\ThirdParty\Win64\nvngx_dlssg.dll

**Comment by Recol** [comment]
@ghuff07 I've added it to the whitelist many thanks, feel free to report if it happens again.
