### ISSUE TITLE
Dark and Darker's anti-cheat flags the updated dlss.dll file as suspicious activity and closes the game.

### ISSUE THREAD

**Issue by Gr4yTempest** [Recol/DLSS-Updater#39]
Title basically, but I should probably mention that the anti-cheat doesn't ban you, so that's fortunate. Should probably add DaD to the Book of Grudges.

**Comment by Recol** [comment]
@Gr4yTempest Would you mind reporting the file structure (i.e. the full installation path) of where the game is installed so i can exclude it thanks.

**Comment by Gr4yTempest** [comment]
D:\Steam\steamapps\common\Dark and Darker
Like so? If this isn't what you're looking for could you explain further?

**Comment by Recol** [comment]
@Gr4yTempest Yup that's great thanks, i've added it to the whitelist so it should be excluded, please report back if this doesn't happen.
