### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by jaredcat** [Recol/DLSS-Updater#4]
Would love to be able to install and update this via [chocolatey](https://docs.chocolatey.org/en-us/features/create-packages/)

**Comment by Recol** [comment]
Like the idea, the build scripts are a bit of a mess and something more coherent would definitely be useful.

**Comment by Recol** [comment]
@jaredcat Small update, i have deployed support for Chocolatey, it is currently going through validation, so may take a few days, will feedback once it's finished.

**Comment by Recol** [comment]
Available at https://community.chocolatey.org/packages/dlss-updater/2.2.2

**Comment by jaredcat** [comment]
If anyone is curious in trying to install it while it's under review `choco install dlss-updater --version=2.2.2`

@Recol its a little of a nit but it would be nice if the exe's name was all lower case to make it easier to run via cmd

**Comment by Recol** [comment]
@jaredcat Will have a think cheers, no guarantee though, hope you enjoy it.
