### ISSUE TITLE
DLSS 3 Frame Generation dll version 3.8.1 got released recently.

### ISSUE THREAD

**Issue by Gr4yTempest** [Recol/DLSS-Updater#46]
This is probably already on your radar, but just in case it isn't I wanted to ask if you could update the **Frame Gen** dll to the latest version. I hope this post doesn't come across as nagging.

**Comment by Recol** [comment]
@Gr4yTempest Thanks for the info, will release an update soon.

**Comment by Recol** [comment]
@Gr4yTempest This is now included in version 2.5.1: https://github.com/Recol/DLSS-Updater/releases/tag/V2.5.1 thanks.
