### ISSUE TITLE
Doesnt do anything for Xbox Live Games Folder

### ISSUE THREAD

**Issue by Wontell** [Recol/DLSS-Updater#47]
Can support for XBL be added? Right now if I add the folder as custom, it doesn't detect games.

P.S. Unrelated to above: I had some Failed errors for some Steam games like Lifes of P, The Last of Us, atomic heart and 3 more

**Comment by Recol** [comment]
@Wontell There's no official support for Xbox Game Pass games, these files use a different file structure to the others and there isn't an easy way to override it. You can use a custom folder for these **from** the launcher which may work but it is guaranteed not to work from the default folder structure.

Errors are normal and to be expected. Please read the documentation for which games do not qualify: https://github.com/Recol/DLSS-Updater?tab=readme-ov-file#whitelisted-games

**Comment by Wontell** [comment]
> @Wontell There's no official support for Xbox Game Pass games, these files use a different file structure to the others and there isn't an easy way to override it as of now. You can use a custom folder for these **from** the launcher which may work but it is guaranteed not to work from the default folder structure.
> 
> Errors are normal and to be expected (assuming it meets the criteria that's expected). Please read the documentation for which games do not qualify: https://github.com/Recol/DLSS-Updater?tab=readme-ov-file#whitelisted-games, if it explicitly does not fit this then attach the log file and i can take a look.

Hi,
wasn't xbox files updated to be like standard folder structure? At least thats what i have, i can  replace the DLSS files manually, it works
for example Indiana johns DLSS files here: F:\XboxGames\Indiana Jones and the Great Circle\Content\streamline\

**Comment by Wontell** [comment]
[dlss_updater.log](https://github.com/user-attachments/files/18199839/dlss_updater.log)


Here is the original log file

**Comment by Recol** [comment]
@Wontell As mentioned please try this with version 2.5.2, the issue i can see in the logs was resolved by this for Atomic Heart etc.

**Comment by Recol** [comment]
@Wontell Just as a FYI Xbox support is now included from version 2.6.0 onwards thanks.

**Comment by Wontell** [comment]
> @Wontell Just as a FYI Xbox support is now included from version 2.6.0 onwards thanks.

Great, thanks!
