### ISSUE TITLE
Final Fantasy XV DLSS 1.0

### ISSUE THREAD

**Issue by Neoniq** [Recol/DLSS-Updater#5]
Why is version  below 2.0 is not supported? Is it possible to manually replace dll?

**Comment by lucaskiu** [comment]
And Monster hunter world too, use dlss 1.1 version. I wanted see how stay in new version dlss. Sad :/ 
![updater](https://github.com/user-attachments/assets/f669eb15-5b31-4ad5-a2ed-39d65c21e7c8)

**Comment by Recol** [comment]
Games that use <2 on the DLL **cannot** be updated, this is required by the game developer, they are excluded to make sure the game boots.
