### ISSUE TITLE
failed update in all ea games

### ISSUE THREAD

**Issue by Yapalaplace** [Recol/DLSS-Updater#8]
idk why, but all of the dlss update failed for my battlefield games : battlefield V and Battlefielkd 2042. If that can help you debug it, i can provide information or logs or whatever you need.

Thanks for that awesome project!

**Comment by Recol** [comment]
@Yapalaplace If you can provide logs here I can take a look at the problem thanks.

**Comment by Yapalaplace** [comment]
Python executable: C:\Users\trist\Downloads\DLSS.Updater.1.5.5\DLSS_Updater.exe
sys.path: ['C:\\Users\\trist\\Downloads\\DLSS.Updater.1.5.5', 'C:\\Users\\trist\\Downloads\\DLSS.Updater.1.5.5\\_internal\\base_library.zip', 'C:\\Users\\trist\\Downloads\\DLSS.Updater.1.5.5\\_internal\\lib-dynload', 'C:\\Users\\trist\\Downloads\\DLSS.Updater.1.5.5\\_internal']
DLSS Updater version 1.5.5
Checking for updates...
Checking for updates...
No updates available. You have the latest version.
Looking for release notes at: C:\Users\trist\Downloads\DLSS.Updater.1.5.5\_internal\release_notes.txt

Release Notes:

Version 1.4.0:
Updated the NVGX DLL to version 3.7.20.
Changed the acceptance for skipping to use the Enter key than typing N/A.
Formatting fixes.

Version 1.4.1:
Add note about manual update downloads.

Version 1.5.0:
Refactor code to use concurrency to speed up I/O related operations for updating multiple folders.
Introduced DLL tracking for proper handling of await and async handling operations.
Minor bug fixes and cleanups.

Version 1.5.1:
Minor update note fixes.

Version 1.5.2:
Add exclusion for DLSS DLL's which are less than 2.0.

Version 1.5.3:
Logging messaging cleanup to be more useful when updating a DLL.

Version 1.5.5:
Whitelist updated to account for Delta Force, Monster Hunter World, Fortnite, and The First Descendant.
Updated the license to migrate to the Apache 2.0 from the BY-SA.
Logging improvements for clarity.
Add experimental EAC global block into the code, do not enable though.
Found DLSS DLL in Steam: C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll
Found DLSS DLL in Steam: C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\nvngx_dlss.dll
Found DLSS DLL in Steam: C:\Program Files (x86)\Steam\steamapps\common\Overwatch\nvngx_dlss.dll
Found DLSS DLL in Steam: C:\Program Files (x86)\Steam\steamapps\common\The Finals\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll
Please enter the path for EA games or press Enter to skip: C:\Program Files\EA Games
Found DLSS DLL in EA Launcher: C:\Program Files\EA Games\Battlefield 2042\nvngx_dlss.dll
Found DLSS DLL in EA Launcher: C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll
Please enter the path for Epic Games or press Enter to skip:
Please enter the path for GOG games or press Enter to skip:
Please enter the path for Battle.net games or press Enter to skip:
Found DLLs in the following launchers:
Steam:
 - C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll
 - C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\nvngx_dlss.dll
 - C:\Program Files (x86)\Steam\steamapps\common\Overwatch\nvngx_dlss.dll
 - C:\Program Files (x86)\Steam\steamapps\common\The Finals\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll
EA Launcher:
 - C:\Program Files\EA Games\Battlefield 2042\nvngx_dlss.dll
 - C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll

Updating DLLs...
Checking DLL at C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll...
Existing version: 3,7,20,0, Latest version: 3,7,20,0
C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll is already up-to-date (version 3,7,20,0).
Checking DLL at C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\nvngx_dlss.dll...
Existing version: 3,7,20,0, Latest version: 3,7,20,0
C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\nvngx_dlss.dll is already up-to-date (version 3,7,20,0).
Checking DLL at C:\Program Files (x86)\Steam\steamapps\common\Overwatch\nvngx_dlss.dll...
Existing version: 3,7,20,0, Latest version: 3,7,20,0
C:\Program Files (x86)\Steam\steamapps\common\Overwatch\nvngx_dlss.dll is already up-to-date (version 3,7,20,0).
Checking DLL at C:\Program Files (x86)\Steam\steamapps\common\The Finals\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll...
Existing version: 3,7,20,0, Latest version: 3,7,20,0
C:\Program Files (x86)\Steam\steamapps\common\The Finals\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll is already up-to-date (version 3,7,20,0).
Checking DLL at C:\Program Files\EA Games\Battlefield 2042\nvngx_dlss.dll...
Existing version: 3,7,20,0, Latest version: 3,7,20,0
C:\Program Files\EA Games\Battlefield 2042\nvngx_dlss.dll is already up-to-date (version 3,7,20,0).
Checking DLL at C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll...
Existing version: 1,0,13,0, Latest version: 3,7,20,0
Skipping update for C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll: Version 1,0,13,0 is less than 2.0.0 and cannot be updated.
Failed to update DLSS DLL at C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll.
Failed to update DLSS DLL at C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\nvngx_dlss.dll.
Failed to update DLSS DLL at C:\Program Files (x86)\Steam\steamapps\common\Overwatch\nvngx_dlss.dll.
Failed to update DLSS DLL at C:\Program Files (x86)\Steam\steamapps\common\The Finals\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll.
Failed to update DLSS DLL at C:\Program Files\EA Games\Battlefield 2042\nvngx_dlss.dll.
Failed to update DLSS DLL at C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll.
DLL updates completed.

Summary:
No games were updated.

Games skipped:
 - Assetto Corsa Competizione - Steam (Reason: Update failed)
 - Lethal Company - Steam (Reason: Update failed)
 - Overwatch - Steam (Reason: Update failed)
 - The Finals - Steam (Reason: Update failed)
 - Battlefield 2042 - EA Launcher (Reason: Update failed)
 - Battlefield V - EA Launcher (Reason: Update failed)

Press Enter to exit...

**Comment by Yapalaplace** [comment]
Where can i find the logs?

**Comment by Recol** [comment]
> Existing version: 1,0,13,0, Latest version: 3,7,20,0
Skipping update for C:\Program Files\EA Games\Battlefield V\nvngx_dlss.dll: Version 1,0,13,0 is less than 2.0.0 and cannot be updated.

This is normal and not a limitation for this program, DLSS versions which are less than version `2.0` cannot be updated except by implementation of the game developer, I realise this isn't exactly clear so I will update the error message to clarify this.

The program is saying that the rest of the DLL's are already version 3.7.20, could you right click the DLL's for one of these to see if this is the case or not and show a screenshot.
